title: "Andy的日记"
description: "记录每一天的生活点滴"
author: "Andy Zou"
email: "1490229633@qq.com"

# Jekyll 主题（可选）
theme: minima

# 基础设置
baseurl: ""           # 如果是用户名.github.io，留空
url: "https://lmqc.github.io"

# 分页设置（可选）
paginate: 10
paginate_path: "/page:num/"

# 插件
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

# 其他
timezone: Asia/Shanghai
